MAGE-947: restrict recommend CSS to algolia managed blocks
algolia/algoliasearch-magento-2 pull request #1553
Opened 2024-06-28 15:30 UTC by damcou

This PR ports the change suggested by @sgeleon here: https://github.com/algolia/algoliasearch-magento-2/pull/1514

- Added a #algoliaRecommend block which acts as a parent for each recommend block
- Applied CSS on the recommend blocks, taking into account the newly created parent block

2024-07-01 13:20 UTC, cammonro requested changes

2024-07-01 13:20 UTC, cammonro commented on view/frontend/web/internals/recommend.css
> +#algoliaRecommend .recommend-component {
👍 

To be absolutely safe, I think we should apply this specificity to _all_ Algolia Recommend related DOM elements.

2024-07-02 19:50 UTC, cammonro approved these changes

2024-07-03 03:14 UTC, mrahman3177 approved these changes
Looks good. Good Job!

2024-07-03 09:26 UTC, merged