MAGE-909: algoliaLastUpdateAtCET time changed to UTC timestamp
algolia/algoliasearch-magento-2 pull request #1557
Opened 2024-07-02 19:30 UTC by mrahman3177

**Summary**

algoliaLastUpdateAtCET time changed to UTC timestamp 
<img width="1238" alt="Screenshot 2024-07-02 at 3 28 49 PM" src="https://github.com/algolia/algoliasearch-magento-2/assets/167926401/7a93c02e-10c5-4d61-9552-e956308d92ab">

2024-07-02 19:41 UTC, cammonro requested changes
Let's also be sure to convert `created_at` to UTC as well.

2024-07-10 17:23 UTC, cammonro approved these changes

2024-07-24 14:08 UTC, merged

2024-08-29 18:55 UTC, amcguireweb commented
This should check if `$object['created_at']` is set before running `strtotime()` or you will not be able to successfully reindex the algolia indices.

> ERROR: Exception: Warning: Undefined array key "created_at" in /var/www/html/vendor/algolia/algoliasearch-magento-2/Helper/AlgoliaHelper.php on line 596 in /var/www/html/vendor/magento/framework/App/ErrorHandler.php:62

2024-08-29 19:01 UTC, cammonro commented
You're right @amcguireweb. This has been fixed in [`3.14.1`](https://github.com/algolia/algoliasearch-magento-2/tree/3.14.1-rc2). We've just been waiting on Adobe to release to Marketplace, but feel free to pull the latest version from Github or apply [this patch](https://patch-diff.githubusercontent.com/raw/algolia/algoliasearch-magento-2/pull/1586.diff).

cc @mrahman3177