MAGE-1057: Fix/add product tests
algolia/algoliasearch-magento-2 pull request #1626
Opened 2024-10-07 16:18 UTC by damcou

This PR contains:

- Fixed the `ProductsIndexingTest.php` file
- Added our own data fixture which adds 1 website, 2 stores and assign some products to them
- Added the `MultiStoreProductsTest.php` file for multi-stores scenarios.

⚠️ : 2 comments:
- The data fixture generates some (non-blocking) noise in the console because the extension asks for credentials, this will disappear once the multi-app work will be added to the extension.
- Some tests regarding query rules will be added later but in the MultiStoreConfig class since we don't need to index products for this.

2024-10-09 04:07 UTC, cammonro requested changes
Great work here @damcou 🙌 

I know integration testing is super tedious but this brings a lot of improvement towards test automation and introducing custom fixtures is super helpful.

I also ran the tests and got some inconsistent green / red results so I made a few suggestions. Other comments are just non blocking questions/observations.

Test results:
- `MultiStoreProductsTest` - successful test consistently 
- `ProductsIndexingTest` - 1 error on first pass on 2.4.6, success on 2.4.7, 2 errors on second pass - due to a tear down issue I think?
![image](https://github.com/user-attachments/assets/102188f8-fa93-432a-a0e8-bcc61052eeaa)
- `MultiStoreConfigTest` - works sometimes and sometimes not - I'm suspecting read/write latency?
![image](https://github.com/user-attachments/assets/5d81d080-ddaf-4d65-a39e-b2bd043ca338)

2024-10-09 08:35 UTC, damcou commented on Test/Integration/AssertValues/Magento246.php
>      public $productsOutOfStockCount = 181;
Interesting, I'm going to make more tests with 2.4.6 👍

2024-10-09 08:49 UTC, damcou commented on Test/Integration/Config/MultiStoreConfigTest.php
> +        $this->assertEquals($indicesCreatedByTest, 21);
Nice catch ! I guess I have a bunch of tests to change ;)

2024-10-09 08:57 UTC, damcou commented on Test/Integration/Config/MultiStoreConfigTest.php
>          $this->indicesConfigurator->saveConfigurationToAlgolia($fixtureSecondStore->getId());
I added some `waitLastTask()` calls in the `saveConfigurationToAlgolia()` method itself following this [discussion](https://github.com/algolia/algoliasearch-magento-2/pull/1620#discussion_r1773429344) but I guess it doesn't cost that much to add one more here.

2024-10-09 08:57 UTC, damcou commented on Test/Integration/Config/MultiStoreConfigTest.php
> +        $this->setConfig(ConfigHelper::IS_INSTANT_ENABLED, 0);
Found this good idea while reading your PR actually ;)

2024-10-09 09:00 UTC, damcou commented on Test/Integration/Product/ProductsIndexingTest.php
> +            'special_from_date' => date($priceFrom),
Good catch !

2024-10-09 09:02 UTC, damcou commented on Test/Integration/_files/second_website_with_two_stores_and_products.php
Little bit of context : I originally tried to assign the products during the tests and for some reason it took forever, making the tests way longer to run. I guess it has something to do with DB isolation (which is still a little bit blurry for me TBH)

2024-10-09 09:04 UTC, damcou commented on Test/Integration/_files/second_website_with_two_stores_and_products_rollback.php
No this is the standard way of handling fixture cleanup after the tests : https://developer.adobe.com/commerce/testing/guide/integration/annotations/magento-data-fixture/#fixture-rollback (this file is just a copy/paste of the fixture found in the Magento core tests)

2024-10-09 09:31 UTC, damcou commented on Test/Integration/Product/MultiStoreProductsTest.php
> + * @magentoDataFixture ../../../../app/code/Algolia/AlgoliaSearch/Test/Integration/_files/second_website_with_two_stores_and_products.php
Very good catch ! Completely forgot about that

2024-10-09 09:45 UTC, damcou commented on Test/Integration/Product/MultiStoreProductsTest.php
> + * @magentoDbIsolation disabled
I tried to run the tests without it and I got some errors like

`SQLSTATE[HY000]: General error: 1412 Table definition has changed, please retry transaction`

TBH, I'm not fully sure why it's needed here, but I'm just happy that this solves this issue ;)

2024-10-09 09:51 UTC, damcou commented
@cammonro Thanks a lot for this thorough review, I made a first batch of changes, regarding the test failures : 
- Need to investigate more regarded expected values on 2.4.6
- Special price flakiness seems to be solved by the introduced change
- I can reproduce the flakiness regarding Rule creation, I need to find a solution for this.

2024-10-09 13:18 UTC, cammonro commented on Test/Integration/Product/MultiStoreProductsTest.php
> + * @magentoDbIsolation disabled
Good to know! I wonder if that error is somehow similar to the transaction conflicts I saw with the queue tests.  I think the isolation is nice for simple tests but with more complex operations it seems best to manage the process explicitly even though it's more tedious to tear down everything after.

2024-10-09 13:20 UTC, cammonro commented on Test/Integration/_files/second_website_with_two_stores_and_products.php
Yes I think you might be right. Maybe some row locking was happening because of the database transactions.

2024-10-09 13:22 UTC, cammonro commented on Test/Integration/_files/second_website_with_two_stores_and_products_rollback.php
Ah! That makes total sense that you would need to instruct the runner on how to tear down the fixture as well as build it. 
I learned something! 🤓 
Thanks for sharing that.

2024-10-10 14:00 UTC, cammonro approved these changes
Super duper! 🚀 
<img width="1482" alt="image" src="https://github.com/user-attachments/assets/48857965-39df-4b63-b0a5-bf10f2031a09">
<img width="1483" alt="image" src="https://github.com/user-attachments/assets/bbfa16ff-352e-4857-8395-5ca00747fc4a">

2024-10-10 14:00 UTC, cammonro commented on Test/Integration/TestCase.php
> +            if ($this->getMagentEdition() === 'Community') {
Ah ha! Mystery solved 🕵️‍♂️ 🎉

2024-10-10 14:32 UTC, merged