MAGE-1050: category search test included.
algolia/algoliasearch-magento-2 pull request #1628
Opened 2024-10-09 23:55 UTC by mrahman3177

**Summary**

Category search integration test included.
<img width="710" alt="Screenshot 2024-10-09 at 7 55 36 PM" src="https://github.com/user-attachments/assets/b0dc9d4f-1dc5-42da-8224-a69b634650d0">

2024-10-10 18:54 UTC, cammonro commented on Test/Integration/Search/SearchTest.php
>          $this->assertNotEmpty($results);
Can we verify that the number of products retrieved with the category facet matches was is expected - perhaps against a collection through `CategoryRepository` and then verify parity with the Algolia index? i.e. counts should be identical. Keep in mind other settings such as whether included in menu etc'.

2024-10-10 18:56 UTC, cammonro commented on Test/Integration/Search/SearchTest.php
> +        list($results, $totalHits, $facetsFromAlgolia) = $this->helper->getSearchResult('', 1);
Let's broaden our test cases a little to actually verify that expected products, skus, and colors are found against certain assertion values and not just that there are results.

2024-10-10 18:57 UTC, cammonro requested changes
Please see comments in PR and Jira.

2024-10-14 15:07 UTC, damcou reviewed
Tested locally and it works as expected ! 🙌 
Just need to make 2 small updates I think, good job overall !

2024-10-14 15:07 UTC, damcou commented on Test/Integration/Search/SearchTest.php
> +            'facetFilters' => ['categoryIds:' . $this->assertValues->expectedCategory]
`expectedCategory` is in fact the expected number of categories indexed in the Algolia dashboard and not an actual ID . I guess `$this->assertValues->expectedCategory` is quite missleading 😄 . 

Feel free to use a `const` in the class to arbitrary search for a category id (like we did in newly created tests) : https://github.com/algolia/algoliasearch-magento-2/blob/release/3.14.3/Test/Integration/Category/MultiStoreCategoriesTest.php#L31

2024-10-14 15:07 UTC, damcou commented on Test/Integration/Search/SearchTest.php
> +            ->addCategoriesFilter(["in" => $this->assertValues->expectedCategory])
To be replaced here as well :)

2024-10-15 08:14 UTC, damcou approved these changes
LGTM, good work ! 🙌

2024-10-15 13:23 UTC, merged